// <auto-generated />
using DroneComponentsInventory.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DroneComponentsInventory.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260126083323_AddPriceToFcComponent")]
    partial class AddPriceToFcComponent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("DroneComponentsInventory.Models.BatteryComponent", b =>
                {
                    b.Property<int>("BatteryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("battery_id");

                    b.Property<string>("BalanceConnector")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("balance_connector");

                    b.Property<double>("BurstRateC")
                        .HasColumnType("REAL")
                        .HasColumnName("burst_rate_c");

                    b.Property<int>("CapacityMah")
                        .HasColumnType("INTEGER")
                        .HasColumnName("capacity_mah");

                    b.Property<int>("CellCountS")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cell_count_s");

                    b.Property<string>("Chemistry")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("chemistry");

                    b.Property<string>("DischargeConnector")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("discharge_connector");

                    b.Property<double>("DischargeRateC")
                        .HasColumnType("REAL")
                        .HasColumnName("discharge_rate_c");

                    b.Property<double>("HeightMm")
                        .HasColumnType("REAL")
                        .HasColumnName("height_mm");

                    b.Property<double>("LengthMm")
                        .HasColumnType("REAL")
                        .HasColumnName("length_mm");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<decimal>("NominalVoltageV")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("nominal_voltage_v");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<double>("WeightG")
                        .HasColumnType("REAL")
                        .HasColumnName("weight_g");

                    b.Property<double>("WidthMm")
                        .HasColumnType("REAL")
                        .HasColumnName("width_mm");

                    b.HasKey("BatteryId");

                    b.ToTable("battery_components");
                });

            modelBuilder.Entity("DroneComponentsInventory.Models.ESCComponent", b =>
                {
                    b.Property<int>("EscId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("esc_id");

                    b.Property<decimal?>("ContinuousCurrentA")
                        .HasColumnType("TEXT")
                        .HasColumnName("continuous_current_a");

                    b.Property<string>("EscType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<int?>("MountPatternMm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mount_pattern_mm");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<string>("SupportedProtocols")
                        .HasColumnType("TEXT")
                        .HasColumnName("supported_protocols");

                    b.Property<int?>("VoltageInputS")
                        .HasColumnType("INTEGER")
                        .HasColumnName("voltage_input_s");

                    b.Property<int?>("WeightG")
                        .HasColumnType("INTEGER")
                        .HasColumnName("weight_g");

                    b.HasKey("EscId");

                    b.ToTable("esc_components");
                });

            modelBuilder.Entity("DroneComponentsInventory.Models.FCComponent", b =>
                {
                    b.Property<int>("FcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("fc_id");

                    b.Property<string>("FirmwareSupport")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("firmware_support");

                    b.Property<string>("ImuGyro")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("imu_gyro");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer");

                    b.Property<string>("McuProcessor")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("mcu_processor");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("MountPatternMm")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("mount_pattern_mm");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<string>("VoltageInputS")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("voltage_input_s");

                    b.Property<decimal?>("WeightG")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("weight_g");

                    b.HasKey("FcId");

                    b.ToTable("fc_components");
                });

            modelBuilder.Entity("DroneComponentsInventory.Models.FPVCameraComponent", b =>
                {
                    b.Property<int>("CameraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("camera_id");

                    b.Property<string>("FovModes")
                        .HasColumnType("TEXT")
                        .HasColumnName("fov_modes");

                    b.Property<decimal?>("LensFocalMm")
                        .HasColumnType("TEXT")
                        .HasColumnName("lens_focal_mm");

                    b.Property<decimal?>("LowLightLux")
                        .HasColumnType("TEXT")
                        .HasColumnName("low_light_lux");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<int?>("MountSizeMm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mount_size_mm");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<int?>("ResolutionTvl")
                        .HasColumnType("INTEGER")
                        .HasColumnName("resolution_tvl");

                    b.Property<string>("SensorSize")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("sensor_size");

                    b.Property<string>("SupportedAspectRatios")
                        .HasColumnType("TEXT")
                        .HasColumnName("supported_aspect_ratios");

                    b.Property<string>("TypeSystem")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("type_system");

                    b.Property<decimal?>("WeightG")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("weight_g");

                    b.HasKey("CameraId");

                    b.ToTable("fpv_camera_components");
                });

            modelBuilder.Entity("DroneComponentsInventory.Models.FPVGogglesComponent", b =>
                {
                    b.Property<int>("FPVGogglesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("fpv_goggles_id");

                    b.Property<double?>("BatteryLifeHours")
                        .HasColumnType("REAL")
                        .HasColumnName("battery_life_hours");

                    b.Property<string>("DisplayType")
                        .HasColumnType("TEXT")
                        .HasColumnName("display_type");

                    b.Property<int?>("DiversityAntennas")
                        .HasColumnType("INTEGER")
                        .HasColumnName("diversity_antennas");

                    b.Property<bool?>("DvrCapability")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dvr_capability");

                    b.Property<bool?>("IPDAdjustable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ipd_adjustable");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("latency_ms");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("PowerInput")
                        .HasColumnType("TEXT")
                        .HasColumnName("power_input");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("ReceiverType")
                        .HasColumnType("TEXT")
                        .HasColumnName("receiver_type");

                    b.Property<string>("Resolution")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolution");

                    b.Property<double?>("ScreenSizeInch")
                        .HasColumnType("REAL")
                        .HasColumnName("screen_size_inch");

                    b.Property<string>("VideoSystem")
                        .HasColumnType("TEXT")
                        .HasColumnName("video_system");

                    b.Property<int?>("WeightGrams")
                        .HasColumnType("INTEGER")
                        .HasColumnName("weight_g");

                    b.HasKey("FPVGogglesId");

                    b.ToTable("fpv_goggles_components");
                });

            modelBuilder.Entity("DroneComponentsInventory.Models.FrameComponent", b =>
                {
                    b.Property<int>("FrameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("frame_id");

                    b.Property<int?>("ArmThicknessMm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("arm_thickness_mm");

                    b.Property<string>("FcMountPattern")
                        .HasColumnType("TEXT")
                        .HasColumnName("fc_mount_pattern");

                    b.Property<int?>("FrameWeightG")
                        .HasColumnType("INTEGER")
                        .HasColumnName("frame_weight_g");

                    b.Property<string>("Geometry")
                        .HasColumnType("TEXT")
                        .HasColumnName("geometry");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT")
                        .HasColumnName("material");

                    b.Property<double?>("MaxPropInch")
                        .HasColumnType("REAL")
                        .HasColumnName("max_prop_inch");

                    b.Property<int?>("MaxStackHeightMm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_stack_height_mm");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("MotorMountPattern")
                        .HasColumnType("TEXT")
                        .HasColumnName("motor_mount_pattern");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<int?>("WheelbaseMm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("wheelbase_mm");

                    b.HasKey("FrameId");

                    b.ToTable("frame_components");
                });

            modelBuilder.Entity("DroneComponentsInventory.Models.MotorsComponent", b =>
                {
                    b.Property<int>("MotorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Kv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MaxThrustGrams")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MountPattern")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RecommendedPropInch")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecommendedVoltageS")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("StatorSizeMm")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("WeightGrams")
                        .HasColumnType("TEXT");

                    b.HasKey("MotorId");

                    b.ToTable("MotorsComponents");
                });

            modelBuilder.Entity("DroneComponentsInventory.Models.PropellersComponent", b =>
                {
                    b.Property<int>("PropellerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("propeller_id");

                    b.Property<int>("BladeCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("blade_count");

                    b.Property<string>("ColorOptions")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("color_options");

                    b.Property<int>("DiameterMm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("diameter_mm");

                    b.Property<string>("FrameClass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("frame_class");

                    b.Property<int>("IncludedQuantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("included_quantity");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("material");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<decimal>("PitchInch")
                        .HasColumnType("TEXT")
                        .HasColumnName("pitch_inch");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("RecommendedMotorKv")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recommended_motor_kv");

                    b.Property<string>("RecommendedMotorSize")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("recommended_motor_size");

                    b.Property<string>("RotationDirection")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("rotation_direction");

                    b.Property<decimal>("ShaftDiameterMm")
                        .HasColumnType("TEXT")
                        .HasColumnName("shaft_diameter_mm");

                    b.Property<decimal>("WeightG")
                        .HasColumnType("TEXT")
                        .HasColumnName("weight_g");

                    b.HasKey("PropellerId");

                    b.ToTable("propellers_components");
                });

            modelBuilder.Entity("DroneComponentsInventory.Models.RadioControllerComponent", b =>
                {
                    b.Property<int>("RadioControllerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("radio_controller_id");

                    b.Property<string>("BatteryType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("battery_type");

                    b.Property<string>("ControllerStyle")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("controller_style");

                    b.Property<string>("FirmwareSupport")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("firmware_support");

                    b.Property<decimal?>("FrequencyGhz")
                        .HasColumnType("decimal(6,3)")
                        .HasColumnName("frequency_ghz");

                    b.Property<string>("GimbalType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("gimbal_type");

                    b.Property<int?>("HeightMm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height_mm");

                    b.Property<int?>("LengthMm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("length_mm");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer");

                    b.Property<int?>("MaxChannels")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_channels");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<decimal?>("OutputPowerMw")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("output_power_mw");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<string>("ProtocolsSupported")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("protocols_supported");

                    b.Property<string>("ScreenType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("screen_type");

                    b.Property<bool?>("TelemetrySupport")
                        .HasColumnType("INTEGER")
                        .HasColumnName("telemetry_support");

                    b.Property<decimal?>("WeightG")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("weight_g");

                    b.Property<int?>("WidthMm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width_mm");

                    b.HasKey("RadioControllerId");

                    b.ToTable("radio_controller_components");
                });

            modelBuilder.Entity("DroneComponentsInventory.Models.ReceiverAntennaComponent", b =>
                {
                    b.Property<int>("ReceiverAntennaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("receiver_antenna_id");

                    b.Property<int?>("CableLengthMm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cable_length_mm");

                    b.Property<string>("CompatibleReceivers")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("compatible_receivers");

                    b.Property<string>("Connector")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("connector");

                    b.Property<string>("ConnectorGender")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("connector_gender");

                    b.Property<string>("FrequencyBand")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("frequency_band");

                    b.Property<decimal?>("GainDbi")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("gain_dbi");

                    b.Property<int?>("LengthMm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("length_mm");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("MountType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("mount_type");

                    b.Property<string>("Polarization")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("polarization");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<string>("RadiationPattern")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("radiation_pattern");

                    b.Property<decimal?>("WeightG")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("weight_g");

                    b.HasKey("ReceiverAntennaId");

                    b.ToTable("receiver_antenna_components");
                });

            modelBuilder.Entity("DroneComponentsInventory.Models.ReceiverComponent", b =>
                {
                    b.Property<int>("ReceiverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AntennaCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AntennaType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BindingMethod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Channels")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FailsafeSupport")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FrequencyBand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HeightMm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IntendedUse")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LengthMm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModulationProtocol")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MountingType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputSignal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double?>("RangeKm")
                        .HasColumnType("REAL");

                    b.Property<bool>("TelemetrySupport")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("VoltageInputV")
                        .HasColumnType("REAL");

                    b.Property<decimal?>("WeightG")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("WidthMm")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReceiverId");

                    b.ToTable("ReceiverComponents");
                });

            modelBuilder.Entity("DroneComponentsInventory.Models.VideoAntennaComponent", b =>
                {
                    b.Property<int>("AntennaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AntennaClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("AxialRatio")
                        .HasColumnType("REAL");

                    b.Property<string>("Connector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("GainDbi")
                        .HasColumnType("REAL");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatingFrequencyMhz")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Polarization")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("RadiationPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WeightGrams")
                        .HasColumnType("INTEGER");

                    b.HasKey("AntennaId");

                    b.ToTable("VideoAntennaComponents");
                });

            modelBuilder.Entity("DroneComponentsInventory.Models.VideoTransmitterComponent", b =>
                {
                    b.Property<int>("VtxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("vtx_id");

                    b.Property<string>("AntennaConnector")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("antenna_connector");

                    b.Property<string>("ControlProtocols")
                        .HasColumnType("TEXT")
                        .HasColumnName("control_protocols");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer");

                    b.Property<int?>("MaxPowerMw")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_power_mw");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("MountPatternMm")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("mount_pattern_mm");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<decimal?>("VoltageInputS")
                        .HasColumnType("TEXT")
                        .HasColumnName("voltage_input_s");

                    b.Property<decimal?>("WeightG")
                        .HasColumnType("TEXT")
                        .HasColumnName("weight_g");

                    b.HasKey("VtxId");

                    b.ToTable("VideoTransmitterComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
