// <auto-generated />
using System;
using DroneComponentsInventory.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DroneComponentsInventory.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260312113051_FpvCameraLensFocalAndWeightToDouble")]
    partial class FpvCameraLensFocalAndWeightToDouble
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("DroneComponentsInventory.Models.BatteryComponent", b =>
                {
                    b.Property<int>("BatteryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("battery_id");

                    b.Property<string>("BalanceConnector")
                        .HasColumnType("TEXT")
                        .HasColumnName("balance_connector");

                    b.Property<double?>("BurstRateC")
                        .HasColumnType("REAL")
                        .HasColumnName("burst_rate_c");

                    b.Property<int?>("CapacityMah")
                        .HasColumnType("INTEGER")
                        .HasColumnName("capacity_mah");

                    b.Property<int?>("CellCountS")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cell_count_s");

                    b.Property<string>("Chemistry")
                        .HasColumnType("TEXT")
                        .HasColumnName("chemistry");

                    b.Property<string>("DischargeConnector")
                        .HasColumnType("TEXT")
                        .HasColumnName("discharge_connector");

                    b.Property<double?>("DischargeRateC")
                        .HasColumnType("REAL")
                        .HasColumnName("discharge_rate_c");

                    b.Property<int?>("HeightMm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height_mm");

                    b.Property<int?>("LengthMm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("length_mm");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<double?>("NominalVoltageV")
                        .HasColumnType("REAL")
                        .HasColumnName("nominal_voltage_v");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL")
                        .HasColumnName("price");

                    b.Property<int?>("WeightG")
                        .HasColumnType("INTEGER")
                        .HasColumnName("weight_g");

                    b.Property<int?>("WidthMm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width_mm");

                    b.HasKey("BatteryId")
                        .HasName("pk_battery_components");

                    b.ToTable("battery_components", (string)null);
                });

            modelBuilder.Entity("DroneComponentsInventory.Models.DroneBuild", b =>
                {
                    b.Property<int>("BuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("build_id");

                    b.Property<int?>("BatteryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("battery_id");

                    b.Property<int?>("CameraId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("camera_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("EscId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("esc_id");

                    b.Property<int?>("FcId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fc_id");

                    b.Property<int?>("FpvGogglesId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fpv_goggles_id");

                    b.Property<int?>("FrameId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("frame_id");

                    b.Property<int?>("MotorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("motor_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int?>("PropellerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("propeller_id");

                    b.Property<int?>("RadioControllerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("radio_controller_id");

                    b.Property<int?>("ReceiverAntennaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("receiver_antenna_id");

                    b.Property<int?>("ReceiverId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("receiver_id");

                    b.Property<int?>("VideoAntennaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("video_antenna_id");

                    b.Property<int?>("VtxId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vtx_id");

                    b.HasKey("BuildId")
                        .HasName("pk_drone_builds");

                    b.HasIndex("BatteryId")
                        .HasDatabaseName("ix_drone_builds_battery_id");

                    b.HasIndex("CameraId")
                        .HasDatabaseName("ix_drone_builds_camera_id");

                    b.HasIndex("EscId")
                        .HasDatabaseName("ix_drone_builds_esc_id");

                    b.HasIndex("FcId")
                        .HasDatabaseName("ix_drone_builds_fc_id");

                    b.HasIndex("FpvGogglesId")
                        .HasDatabaseName("ix_drone_builds_fpv_goggles_id");

                    b.HasIndex("FrameId")
                        .HasDatabaseName("ix_drone_builds_frame_id");

                    b.HasIndex("MotorId")
                        .HasDatabaseName("ix_drone_builds_motor_id");

                    b.HasIndex("PropellerId")
                        .HasDatabaseName("ix_drone_builds_propeller_id");

                    b.HasIndex("RadioControllerId")
                        .HasDatabaseName("ix_drone_builds_radio_controller_id");

                    b.HasIndex("ReceiverAntennaId")
                        .HasDatabaseName("ix_drone_builds_receiver_antenna_id");

                    b.HasIndex("ReceiverId")
                        .HasDatabaseName("ix_drone_builds_receiver_id");

                    b.HasIndex("VideoAntennaId")
                        .HasDatabaseName("ix_drone_builds_video_antenna_id");

                    b.HasIndex("VtxId")
                        .HasDatabaseName("ix_drone_builds_vtx_id");

                    b.ToTable("drone_builds", (string)null);
                });

            modelBuilder.Entity("DroneComponentsInventory.Models.ESCComponent", b =>
                {
                    b.Property<int>("EscId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("esc_id");

                    b.Property<double?>("ContinuousCurrentA")
                        .HasColumnType("REAL")
                        .HasColumnName("continuous_current_a");

                    b.Property<string>("EscType")
                        .HasColumnType("TEXT")
                        .HasColumnName("esc_type");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<double?>("MountPatternMm")
                        .HasColumnType("REAL")
                        .HasColumnName("mount_pattern_mm");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL")
                        .HasColumnName("price");

                    b.Property<string>("SupportedProtocols")
                        .HasColumnType("TEXT")
                        .HasColumnName("supported_protocols");

                    b.Property<int?>("VoltageInputS")
                        .HasColumnType("INTEGER")
                        .HasColumnName("voltage_input_s");

                    b.Property<double?>("WeightG")
                        .HasColumnType("REAL")
                        .HasColumnName("weight_g");

                    b.HasKey("EscId")
                        .HasName("pk_esc_components");

                    b.ToTable("esc_components", (string)null);
                });

            modelBuilder.Entity("DroneComponentsInventory.Models.FCComponent", b =>
                {
                    b.Property<int>("FcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("fc_id");

                    b.Property<string>("FirmwareSupport")
                        .HasColumnType("TEXT")
                        .HasColumnName("firmware_support");

                    b.Property<string>("ImuGyro")
                        .HasColumnType("TEXT")
                        .HasColumnName("imu_gyro");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer");

                    b.Property<string>("McuProcessor")
                        .HasColumnType("TEXT")
                        .HasColumnName("mcu_processor");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<double?>("MountPatternMm")
                        .HasColumnType("REAL")
                        .HasColumnName("mount_pattern_mm");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL")
                        .HasColumnName("price");

                    b.Property<string>("VoltageInputS")
                        .HasColumnType("TEXT")
                        .HasColumnName("voltage_input_s");

                    b.Property<double?>("WeightG")
                        .HasColumnType("REAL")
                        .HasColumnName("weight_g");

                    b.HasKey("FcId")
                        .HasName("pk_fc_components");

                    b.ToTable("fc_components", (string)null);
                });

            modelBuilder.Entity("DroneComponentsInventory.Models.FPVCameraComponent", b =>
                {
                    b.Property<int>("CameraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("camera_id");

                    b.Property<string>("FovModes")
                        .HasColumnType("TEXT")
                        .HasColumnName("fov_modes");

                    b.Property<double?>("LensFocalMm")
                        .HasColumnType("REAL")
                        .HasColumnName("lens_focal_mm");

                    b.Property<double?>("LowLightLux")
                        .HasColumnType("REAL")
                        .HasColumnName("low_light_lux");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<int?>("MountSizeMm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mount_size_mm");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL")
                        .HasColumnName("price");

                    b.Property<int?>("ResolutionTvl")
                        .HasColumnType("INTEGER")
                        .HasColumnName("resolution_tvl");

                    b.Property<string>("SensorSize")
                        .HasColumnType("TEXT")
                        .HasColumnName("sensor_size");

                    b.Property<string>("SupportedAspectRatios")
                        .HasColumnType("TEXT")
                        .HasColumnName("supported_aspect_ratios");

                    b.Property<string>("TypeSystem")
                        .HasColumnType("TEXT")
                        .HasColumnName("type_system");

                    b.Property<double?>("WeightG")
                        .HasColumnType("REAL")
                        .HasColumnName("weight_g");

                    b.HasKey("CameraId")
                        .HasName("pk_fpv_camera_components");

                    b.ToTable("fpv_camera_components", (string)null);
                });

            modelBuilder.Entity("DroneComponentsInventory.Models.FPVGogglesComponent", b =>
                {
                    b.Property<int>("FpvGogglesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("fpv_goggles_id");

                    b.Property<double?>("BatteryLifeHours")
                        .HasColumnType("REAL")
                        .HasColumnName("battery_life_hours");

                    b.Property<string>("DisplayType")
                        .HasColumnType("TEXT")
                        .HasColumnName("display_type");

                    b.Property<int?>("DiversityAntennas")
                        .HasColumnType("INTEGER")
                        .HasColumnName("diversity_antennas");

                    b.Property<bool>("DvrCapability")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dvr_capability");

                    b.Property<bool>("IpdAdjustable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ipd_adjustable");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("latency_ms");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("PowerInput")
                        .HasColumnType("TEXT")
                        .HasColumnName("power_input");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL")
                        .HasColumnName("price");

                    b.Property<string>("ReceiverType")
                        .HasColumnType("TEXT")
                        .HasColumnName("receiver_type");

                    b.Property<string>("Resolution")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolution");

                    b.Property<double?>("ScreenSizeInch")
                        .HasColumnType("REAL")
                        .HasColumnName("screen_size_inch");

                    b.Property<string>("VideoSystem")
                        .HasColumnType("TEXT")
                        .HasColumnName("video_system");

                    b.Property<int?>("WeightG")
                        .HasColumnType("INTEGER")
                        .HasColumnName("weight_g");

                    b.HasKey("FpvGogglesId")
                        .HasName("pk_fpv_goggles_components");

                    b.ToTable("fpv_goggles_components", (string)null);
                });

            modelBuilder.Entity("DroneComponentsInventory.Models.FrameComponent", b =>
                {
                    b.Property<int>("FrameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("frame_id");

                    b.Property<int?>("ArmThicknessMm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("arm_thickness_mm");

                    b.Property<string>("FcMountPattern")
                        .HasColumnType("TEXT")
                        .HasColumnName("fc_mount_pattern");

                    b.Property<string>("Geometry")
                        .HasColumnType("TEXT")
                        .HasColumnName("geometry");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT")
                        .HasColumnName("material");

                    b.Property<double?>("MaxPropInch")
                        .HasColumnType("REAL")
                        .HasColumnName("max_prop_inch");

                    b.Property<int?>("MaxStackHeightMm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_stack_height_mm");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("MotorMountPattern")
                        .HasColumnType("TEXT")
                        .HasColumnName("motor_mount_pattern");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL")
                        .HasColumnName("price");

                    b.Property<int?>("WeightG")
                        .HasColumnType("INTEGER")
                        .HasColumnName("weight_g");

                    b.Property<int?>("WheelbaseMm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("wheelbase_mm");

                    b.HasKey("FrameId")
                        .HasName("pk_frame_components");

                    b.ToTable("frame_components", (string)null);
                });

            modelBuilder.Entity("DroneComponentsInventory.Models.MotorsComponent", b =>
                {
                    b.Property<int>("MotorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("motor_id");

                    b.Property<int?>("Kv")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kv");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer");

                    b.Property<int?>("MaxThrustG")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_thrust_g");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("MountPattern")
                        .HasColumnType("TEXT")
                        .HasColumnName("mount_pattern");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL")
                        .HasColumnName("price");

                    b.Property<double?>("RecommendedPropInch")
                        .HasColumnType("REAL")
                        .HasColumnName("recommended_prop_inch");

                    b.Property<int?>("RecommendedVoltageS")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recommended_voltage_s");

                    b.Property<double?>("StatorSizeMm")
                        .HasColumnType("REAL")
                        .HasColumnName("stator_size_mm");

                    b.Property<double?>("WeightG")
                        .HasColumnType("REAL")
                        .HasColumnName("weight_g");

                    b.HasKey("MotorId")
                        .HasName("pk_motors_components");

                    b.ToTable("motors_components", (string)null);
                });

            modelBuilder.Entity("DroneComponentsInventory.Models.PropellersComponent", b =>
                {
                    b.Property<int>("PropellerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("propeller_id");

                    b.Property<int?>("BladeCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("blade_count");

                    b.Property<string>("ColorOptions")
                        .HasColumnType("TEXT")
                        .HasColumnName("color_options");

                    b.Property<int?>("DiameterMm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("diameter_mm");

                    b.Property<string>("FrameClass")
                        .HasColumnType("TEXT")
                        .HasColumnName("frame_class");

                    b.Property<int?>("IncludedQuantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("included_quantity");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT")
                        .HasColumnName("material");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<double?>("PitchInch")
                        .HasColumnType("REAL")
                        .HasColumnName("pitch_inch");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL")
                        .HasColumnName("price");

                    b.Property<int?>("RecommendedMotorKv")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recommended_motor_kv");

                    b.Property<string>("RecommendedMotorSize")
                        .HasColumnType("TEXT")
                        .HasColumnName("recommended_motor_size");

                    b.Property<string>("RotationDirection")
                        .HasColumnType("TEXT")
                        .HasColumnName("rotation_direction");

                    b.Property<double?>("ShaftDiameterMm")
                        .HasColumnType("REAL")
                        .HasColumnName("shaft_diameter_mm");

                    b.Property<double?>("WeightG")
                        .HasColumnType("REAL")
                        .HasColumnName("weight_g");

                    b.HasKey("PropellerId")
                        .HasName("pk_propellers_components");

                    b.ToTable("propellers_components", (string)null);
                });

            modelBuilder.Entity("DroneComponentsInventory.Models.RadioControllerComponent", b =>
                {
                    b.Property<int>("RadioControllerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("radio_controller_id");

                    b.Property<string>("BatteryType")
                        .HasColumnType("TEXT")
                        .HasColumnName("battery_type");

                    b.Property<string>("ControllerStyle")
                        .HasColumnType("TEXT")
                        .HasColumnName("controller_style");

                    b.Property<string>("FirmwareSupport")
                        .HasColumnType("TEXT")
                        .HasColumnName("firmware_support");

                    b.Property<double?>("FrequencyGhz")
                        .HasColumnType("REAL")
                        .HasColumnName("frequency_ghz");

                    b.Property<string>("GimbalType")
                        .HasColumnType("TEXT")
                        .HasColumnName("gimbal_type");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer");

                    b.Property<int?>("MaxChannels")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_channels");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<double?>("OutputPowerMw")
                        .HasColumnType("REAL")
                        .HasColumnName("output_power_mw");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL")
                        .HasColumnName("price");

                    b.Property<string>("ProtocolsSupported")
                        .HasColumnType("TEXT")
                        .HasColumnName("protocols_supported");

                    b.Property<string>("ScreenType")
                        .HasColumnType("TEXT")
                        .HasColumnName("screen_type");

                    b.Property<bool>("TelemetrySupport")
                        .HasColumnType("INTEGER")
                        .HasColumnName("telemetry_support");

                    b.Property<int?>("WeightG")
                        .HasColumnType("INTEGER")
                        .HasColumnName("weight_g");

                    b.HasKey("RadioControllerId")
                        .HasName("pk_radio_controller_components");

                    b.ToTable("radio_controller_components", (string)null);
                });

            modelBuilder.Entity("DroneComponentsInventory.Models.ReceiverAntennaComponent", b =>
                {
                    b.Property<int>("ReceiverAntennaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("receiver_antenna_id");

                    b.Property<int?>("CableLengthMm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cable_length_mm");

                    b.Property<string>("CompatibleReceivers")
                        .HasColumnType("TEXT")
                        .HasColumnName("compatible_receivers");

                    b.Property<string>("Connector")
                        .HasColumnType("TEXT")
                        .HasColumnName("connector");

                    b.Property<string>("ConnectorGender")
                        .HasColumnType("TEXT")
                        .HasColumnName("connector_gender");

                    b.Property<string>("FrequencyBand")
                        .HasColumnType("TEXT")
                        .HasColumnName("frequency_band");

                    b.Property<double?>("GainDbi")
                        .HasColumnType("REAL")
                        .HasColumnName("gain_dbi");

                    b.Property<int?>("LengthMm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("length_mm");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("MountType")
                        .HasColumnType("TEXT")
                        .HasColumnName("mount_type");

                    b.Property<string>("Polarization")
                        .HasColumnType("TEXT")
                        .HasColumnName("polarization");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL")
                        .HasColumnName("price");

                    b.Property<string>("RadiationPattern")
                        .HasColumnType("TEXT")
                        .HasColumnName("radiation_pattern");

                    b.Property<int?>("WeightG")
                        .HasColumnType("INTEGER")
                        .HasColumnName("weight_g");

                    b.HasKey("ReceiverAntennaId")
                        .HasName("pk_receiver_antenna_components");

                    b.ToTable("receiver_antenna_components", (string)null);
                });

            modelBuilder.Entity("DroneComponentsInventory.Models.ReceiverComponent", b =>
                {
                    b.Property<int>("ReceiverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("receiver_id");

                    b.Property<int?>("AntennaCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("antenna_count");

                    b.Property<string>("AntennaType")
                        .HasColumnType("TEXT")
                        .HasColumnName("antenna_type");

                    b.Property<string>("BindingMethod")
                        .HasColumnType("TEXT")
                        .HasColumnName("binding_method");

                    b.Property<int?>("Channels")
                        .HasColumnType("INTEGER")
                        .HasColumnName("channels");

                    b.Property<bool>("FailsafeSupport")
                        .HasColumnType("INTEGER")
                        .HasColumnName("failsafe_support");

                    b.Property<string>("FrequencyBand")
                        .HasColumnType("TEXT")
                        .HasColumnName("frequency_band");

                    b.Property<int?>("HeightMm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height_mm");

                    b.Property<string>("IntendedUse")
                        .HasColumnType("TEXT")
                        .HasColumnName("intended_use");

                    b.Property<int?>("LengthMm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("length_mm");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("ModulationProtocol")
                        .HasColumnType("TEXT")
                        .HasColumnName("modulation_protocol");

                    b.Property<string>("MountingType")
                        .HasColumnType("TEXT")
                        .HasColumnName("mounting_type");

                    b.Property<string>("OutputSignal")
                        .HasColumnType("TEXT")
                        .HasColumnName("output_signal");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL")
                        .HasColumnName("price");

                    b.Property<string>("Protocol")
                        .HasColumnType("TEXT")
                        .HasColumnName("protocol");

                    b.Property<double?>("RangeKm")
                        .HasColumnType("REAL")
                        .HasColumnName("range_km");

                    b.Property<bool>("TelemetrySupport")
                        .HasColumnType("INTEGER")
                        .HasColumnName("telemetry_support");

                    b.Property<double?>("VoltageInputV")
                        .HasColumnType("REAL")
                        .HasColumnName("voltage_input_v");

                    b.Property<int?>("WeightG")
                        .HasColumnType("INTEGER")
                        .HasColumnName("weight_g");

                    b.Property<int?>("WidthMm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width_mm");

                    b.HasKey("ReceiverId")
                        .HasName("pk_receiver_components");

                    b.ToTable("receiver_components", (string)null);
                });

            modelBuilder.Entity("DroneComponentsInventory.Models.VideoAntennaComponent", b =>
                {
                    b.Property<int>("AntennaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("antenna_id");

                    b.Property<string>("AntennaClass")
                        .HasColumnType("TEXT")
                        .HasColumnName("antenna_class");

                    b.Property<double?>("AxialRatio")
                        .HasColumnType("REAL")
                        .HasColumnName("axial_ratio");

                    b.Property<string>("Connector")
                        .HasColumnType("TEXT")
                        .HasColumnName("connector");

                    b.Property<double?>("GainDbi")
                        .HasColumnType("REAL")
                        .HasColumnName("gain_dbi");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<double?>("OperatingFrequencyGhz")
                        .HasColumnType("REAL")
                        .HasColumnName("operating_frequency_ghz");

                    b.Property<string>("Polarization")
                        .HasColumnType("TEXT")
                        .HasColumnName("polarization");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL")
                        .HasColumnName("price");

                    b.Property<string>("RadiationPattern")
                        .HasColumnType("TEXT")
                        .HasColumnName("radiation_pattern");

                    b.Property<int?>("WeightG")
                        .HasColumnType("INTEGER")
                        .HasColumnName("weight_g");

                    b.HasKey("AntennaId")
                        .HasName("pk_video_antenna_components");

                    b.ToTable("video_antenna_components", (string)null);
                });

            modelBuilder.Entity("DroneComponentsInventory.Models.VideoTransmitterComponent", b =>
                {
                    b.Property<int>("VtxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("vtx_id");

                    b.Property<string>("AntennaConnector")
                        .HasColumnType("TEXT")
                        .HasColumnName("antenna_connector");

                    b.Property<string>("ControlProtocols")
                        .HasColumnType("TEXT")
                        .HasColumnName("control_protocols");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer");

                    b.Property<double?>("MaxPowerMw")
                        .HasColumnType("REAL")
                        .HasColumnName("max_power_mw");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<int?>("MountPatternMm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mount_pattern_mm");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL")
                        .HasColumnName("price");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<double?>("VoltageInputS")
                        .HasColumnType("REAL")
                        .HasColumnName("voltage_input_s");

                    b.Property<int?>("WeightG")
                        .HasColumnType("INTEGER")
                        .HasColumnName("weight_g");

                    b.HasKey("VtxId")
                        .HasName("pk_video_transmitter_components");

                    b.ToTable("video_transmitter_components", (string)null);
                });

            modelBuilder.Entity("DroneComponentsInventory.Models.DroneBuild", b =>
                {
                    b.HasOne("DroneComponentsInventory.Models.BatteryComponent", "Battery")
                        .WithMany()
                        .HasForeignKey("BatteryId")
                        .HasConstraintName("fk_drone_builds_battery_components_battery_id");

                    b.HasOne("DroneComponentsInventory.Models.FPVCameraComponent", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .HasConstraintName("fk_drone_builds_fpv_camera_components_camera_id");

                    b.HasOne("DroneComponentsInventory.Models.ESCComponent", "Esc")
                        .WithMany()
                        .HasForeignKey("EscId")
                        .HasConstraintName("fk_drone_builds_esc_components_esc_id");

                    b.HasOne("DroneComponentsInventory.Models.FCComponent", "Fc")
                        .WithMany()
                        .HasForeignKey("FcId")
                        .HasConstraintName("fk_drone_builds_fc_components_fc_id");

                    b.HasOne("DroneComponentsInventory.Models.FPVGogglesComponent", "FpvGoggles")
                        .WithMany()
                        .HasForeignKey("FpvGogglesId")
                        .HasConstraintName("fk_drone_builds_fpv_goggles_components_fpv_goggles_id");

                    b.HasOne("DroneComponentsInventory.Models.FrameComponent", "Frame")
                        .WithMany()
                        .HasForeignKey("FrameId")
                        .HasConstraintName("fk_drone_builds_frame_components_frame_id");

                    b.HasOne("DroneComponentsInventory.Models.MotorsComponent", "Motor")
                        .WithMany()
                        .HasForeignKey("MotorId")
                        .HasConstraintName("fk_drone_builds_motors_components_motor_id");

                    b.HasOne("DroneComponentsInventory.Models.PropellersComponent", "Propeller")
                        .WithMany()
                        .HasForeignKey("PropellerId")
                        .HasConstraintName("fk_drone_builds_propellers_components_propeller_id");

                    b.HasOne("DroneComponentsInventory.Models.RadioControllerComponent", "RadioController")
                        .WithMany()
                        .HasForeignKey("RadioControllerId")
                        .HasConstraintName("fk_drone_builds_radio_controller_components_radio_controller_id");

                    b.HasOne("DroneComponentsInventory.Models.ReceiverAntennaComponent", "ReceiverAntenna")
                        .WithMany()
                        .HasForeignKey("ReceiverAntennaId")
                        .HasConstraintName("fk_drone_builds_receiver_antenna_components_receiver_antenna_id");

                    b.HasOne("DroneComponentsInventory.Models.ReceiverComponent", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .HasConstraintName("fk_drone_builds_receiver_components_receiver_id");

                    b.HasOne("DroneComponentsInventory.Models.VideoAntennaComponent", "VideoAntenna")
                        .WithMany()
                        .HasForeignKey("VideoAntennaId")
                        .HasConstraintName("fk_drone_builds_video_antenna_components_video_antenna_id");

                    b.HasOne("DroneComponentsInventory.Models.VideoTransmitterComponent", "Vtx")
                        .WithMany()
                        .HasForeignKey("VtxId")
                        .HasConstraintName("fk_drone_builds_video_transmitter_components_vtx_id");

                    b.Navigation("Battery");

                    b.Navigation("Camera");

                    b.Navigation("Esc");

                    b.Navigation("Fc");

                    b.Navigation("FpvGoggles");

                    b.Navigation("Frame");

                    b.Navigation("Motor");

                    b.Navigation("Propeller");

                    b.Navigation("RadioController");

                    b.Navigation("Receiver");

                    b.Navigation("ReceiverAntenna");

                    b.Navigation("VideoAntenna");

                    b.Navigation("Vtx");
                });
#pragma warning restore 612, 618
        }
    }
}
